version: '3'
services:
  rest:
    container_name: rest
    image: rest/node
    build: node/.
    restart: always
    volumes:
      - ./node:/usr/src/app
    ports:
      - "4001:3008"
    networks:
      - api-bridge
  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27018:27017"
    build: mongo/.
    networks:
        - api-bridge

networks:
  api-bridge:
    driver: bridge
